name: greetings
on:
  issues:
    types: [opened]
permissions:
  issues: write
jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: |
            Hi ! You are awesome !