name: greetings
on:
  issues:
    types: [opened]
permissions:
  issues: write
  pull-requests: write
jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          issue-message: |
            Hello guys ! You are great !
